package org.proiect.model;

public enum TipEchipament {
    //ORTODONTIE
    APARAT_ORTODONTIC, GUTIERA,

    //CHIRURGIE_MAXILO_FACIALA
    PENSA, BISTURIU, DIGA, TUB_DRENAJ, OGLINDA,

    //ENDODONTIE
    POMPA_DRENARE, FREZA, PLOMBA_DEFINITIVA, MICROSCOP,

    //PROTETICA
    SCANNER_3D_AMPRENTA, LINGURA_AMPRENTA, CIMENT
}
