package org.proiect.model;

public enum TipInterventie {
    //ORTODONTIE
    CORECTAREA_MALOCLUZIEI, TRATAREA_BRUXISMULUI,

    //CHIRURGIE_MAXILO_FACIALA
    SINUS_LIFT, DILATARE_BOLTA_PALATINA,

    //ENDODONTIE
    ELIMINARE_INFECTII_CANAL, ELIMINARE_NERV_COMPROMIS,

    //PROTETICA
    MONTARE_FATETE, MONTARE_PROTEZE
}
